### ISSUE TITLE
Help/advice - Panasonic TV

### ISSUE THREAD

**Issue by nodecentral** [Serophots/Lua-AES-256-CBC#1]
Hi,

Long shot …

I’m trying to re-work the Lua code used in the following link to run generically under Lua v5.1, as currently some of it (i think) uses LuaJIT and/or embedded LogicMachine modules/libraries.. https://forum.logicmachine.net/showthread.php?tid=232&pid=16580#pid16580

There’s an encrypt and decrypt payload function referring to aes, cbc, hence I’m wondering how some variation of your code could help ?

Encryption..
````
function encrypt_soap_payload(data, key, hmac_key, iv)
payload = '000000000000'
  n = #data

payload = payload .. string.char(bit.band(bit.rshift(n, 24), 0xFF))
payload = payload .. string.char(bit.band(bit.rshift(n, 16), 0xFF))
payload = payload .. string.char(bit.band(bit.rshift(n, 8), 0xFF))
payload = payload .. string.char(bit.band(n, 0xFF))

payload = payload .. data

 aes_cbc, err = aes:new(key, nil, aes.cipher(128, 'cbc'), { iv = iv }, nil, 1) 
  ciphertext = aes_cbc:encrypt(payload)
  sig = encdec.hmacsha256(ciphertext, hmac_key, true)
  encrypted_payload = encdec.base64enc(ciphertext .. sig)
  return encrypted_payload
end
````
Decryption..
````
function decrypt_soap_payload(data, key, hmac_key, iv)
  aes_cbc, err = aes:new(key, nil, aes.cipher(128, 'cbc'), { iv = iv }, nil, 0) 
  decrypted = aes_cbc:decrypt(encdec.base64dec(data))
  decrypted = string.gsub(string.sub(lmcore.strtohex(decrypted), 33), '%x%x', function(value) return string.char(tonumber(value, 16)) end) 
  return decrypted
end
````

I believe an example command for the encrypt would be along the lines of (2 identified so far, other parameters are still a work in progress :-) ) ..

````
encrypt_soap_payload("<X_PinCode>1234</X_PinCode>",  key,  hmac_key, aUw5WHFRT01ma0ZXejJydmgwWG0rdz09)
````

**Comment by Serophots** [comment]
I would advise using the original Lua Lockbox repository from which the code here was taken. (As it states in the repo description)
More specifically, the code you're referring to uses AES-CBC128 which relates to [this](https://github.com/somesocks/lua-lockbox/blob/master/test/AES128CipherTests.lua) file which should help show you how to use Lua Lockbox and make the appropriate modifications to your code

You can also use the functions [crypt.encrypt](https://github.com/Serophots/Lua-AES-256-CBC/blob/main/main.lua#L1366) / crypt.decrypt in main.lua of this repository which also show directly interacting with Lua Lockbox
^ Note that this code uses a custom [HexPad()](https://github.com/Serophots/Lua-AES-256-CBC/blob/main/main.lua#L1356) function which follows no standards and is not a very robust solution. This is only used to ensure the inputs to AES are of the correct length, and its possible that your use case already has correct length inputs
